.TH start 1 "erts  5.7" "Ericsson AB" "USER COMMANDS"
.SH NAME
start \- UNIX用のOTP起動スクリプトのサンプルスクリプト
.SH DESCRIPTION
.LP
このドキュメントでは、Unix上で組み込みモードのErlangを起動するためのサンプルスクリプトである\fIstart\fRについて説明します。 

.LP
より詳細な使い方については、\fIEmbedded System User\&'s Guide\fR\&をご覧ください。

.SH EXPORTS
.LP
.B
start [ data_file ]
.br
.RS
.LP
.RS 2
.TP 4
.B
data_file:
(オプション)\fIstart_erl\&.data\fRの代わりに使用するデータファイルを指定することができます。

.RE
.LP
環境変数\fIRELDIR\fRで、リリースファイル[?]のパスを指定することができます。
.RE
.SH SEE ALSO
.LP
run_erl(1), start_erl(1)
