.TH werl 1 "erts  5.7" "Ericsson AB" "USER COMMANDS"
.SH NAME
werl \- Erlang のエミュレータ
.SH DESCRIPTION
.LP
Windows上で、Erlangを対話形式で使用するための便利なコマンド:
.LP
\fIwerl <arguments>\fR
.LP
このコマンドは、コマンドラインエディタとスクロールバーの機能を持つウインドウ上で Erlang を実行します。 \fI-oldshell\fR 以外のフラグは erl コマンドと同様に動作します。
.LP
Ctrl-C はテキストをコピーするためのショートカットキーとして予約されています(なお、Ctrl-Vはペースト用に割り当てられています)。実行中のランタイムシステム/シェルプロセスに割り込みをを書けるには、 Ctrl-Break を使用してください。ただし、この挙動はシステムフラグの +B に依存します。
.LP
標準入出力をリダイレクトしたり、 Erlang をパイプラインの中で利用するには、 werl は不適当です。 \fIerl\fR プログラムを代わりに使用するのが良いでしょう。
.LP
\fIwerl\fR ウインドウは、様々な方法で実装されてきましたが、 \fIxterm\fR モデルがコマンドラインベースの対話を行うのに最も適していることがわかりました。
つまり、テキスト選択は矩形で行われるのではなく、行毎に行われます。
The \fIwerl\fR window is in many ways modelled after the \fIxterm\fR window present on other platforms, as the \fIxterm\fR model fits well with line oriented command based interaction\&. This means that selcting text is line oriented rather than rectangle oriented\&.
.LP
\fIwerl\fR ウインドウ内でテキストを選択するには、単純にマウスを左クリックしたままドラッグし、選択したい範囲に動かして下さい。もし選択範囲が行をまたがった場合、選択中のテキストは、選択した行を完全に選択することになります。この挙動はワードプロセッサと同様です。ウインドウに表示されているテキストよりも広い範囲を選択したい場合は、選択したいテキストの開始部分の一部を選択した上で、スクロールバーを押して選択範囲の終点となる場所を表示してください。そして、終点を指した状態で \fI右クリック\fR してください。最初にあなたが選択した場所から、右クリックした場所までが選択されます。
.LP
選択されたテキストは、 \fICtrl-C\fR もしくはツールバーのコピーボタンを押すことでクリップボードにコピーされます。
.LP
入力したテキストは、通常のキーボード入力としてErlangによって解釈されます。
.LP
前に入力したコマンドをもう一度利用するには、 \fI上矢印キー\fR か \fICtrp-P\fR を押してください。また、コマンド履歴がツールバー内のドロップダウンボックスにあります。ドロップダウンボックス内のコマンドを選択することで、プロンプトにそのコマンドを挿入することができます。
.LP
\fIwerl\fR ウインドウを閉じると、 Erlang エミュレータは停止します。

